
# Due to us using the categories for posts then it is advisable to explicitly specify a 
# permalink structure for the site. Otherwise Jekyll attempts to organize the pages in folders
# by the category names and it doesn't understand multi-categories to well :/
permalink: /:categories/:title.html
    #permalink: pretty
    
# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: 'page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2  
  
# Site wide configuration
collections:
  authors:
    output: true
  events:
    output: true
      
title: "Psfedo3"
description: "RCCG Pastor seeds family of Edo province 3"
logo: images/psf-navicon.png
locale: en
url:
feed:
  path: atom.xml

# repo
repository: "psfedo3/psfedo3.github.io"
url: "https://psfedo3.github.io"

# Staticman comments
staticman_url: "https://psfstaticman.herokuapp.com/v2/entry/psfedo3/psfedo3.github.io/source/comments"
staticman_join: "https://psfstaticman.herokuapp.com/v2/entry/psfedo3/psfedo3.github.io/source/seeds"


compress_images:
   images_path: "images/**/*.{gif,png,jpg,jpeg,svg}"
   imageoptim:
     pngout: false
     svgo: true
     verbose: false
  
jekyll-archives:
  enabled: all
  layout: archive
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    category: category-archive
    tag: tag-archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed
  
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-compress-images
  - jekyll-archives

# Site owner
owner:
  name:
  email:
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp

#reCaptcha
reCaptcha:
  siteKey: "6LdvQtYZAAAAAGxXtd7YyTMyxorhY-CIskjjyiQ7" 
  secret: "rvZNSi0JgVsll+jduqG8kWrVk6m12bQYMcfRiOyzZMej241EHPpIZADhqxDIH8rZGCFf5+JlZUt5hdTh0pzcMS4SztztHimRRq2Abdma6BVEHmK51x+/qXCEqhEtCZhEeweOlMkiP9tSBTAN+qZ+Yy9+GoyL0tUfexjXwNOHhhZ5DMFXlzPXukviPwqwSjhFHyMl/d2vJ09QqNWmhmrEETlqnyo1K2+/faoUw+z1MqPIp+5yI1b7VaGN5Z2Syg9JCKkawVsoFVkZxXIE2CbGXY0mYOECIf1O0T/3a6+xD6areipgmg4HQdw5HlmfXoVxyEpuIh3JkkEvNlftnYerqA=="