jekyll_get_json:
  - data: seeds
    json: 'http://getsimpleform.com/messages.js?api_token=d106a0ea4a6e2f746194d0b233704f91'

permalink: /:year/:month/
# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2  
  
# Site wide configuration
collections:
  authors:
    output: true
   
      
title: "Psfedo3"
description: "RCCG Pastor seeds family of Edo province 3"
logo: images/psf-navicon.png
locale: en
url:
feed:
  path: atom.xml

# repo
repository: "psfedo3/psfedo3.github.io"
url: "https://psfedo3.github.io"

# Staticman comments (full configuration in staticman.yml)
staticman:
  branch: "source"


# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed
  
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-get-json

# Site owner
owner:
  name:
  email:
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp

reCaptcha:
  siteKey: "6Ldty9UZAAAAAEfaHK-JDfrUeMLX_YhWMshU2gnG"
  secret: "hg7MBRwH0yuJQDJOKCH9PADn+FfbVXV4hAGJIO3NEueFiCtDKwiiJDTJtZESX5PiPIjEg0U+xd4quipPfKjnA0JGD9p1kq5F9yMIFAf440KeUIMmhWuOhKaIG8qBe13syB0CmAgAeqi3Vzy5/+ThxZPu5k/SZkrmFuo7IydJEpU="
